# config.toml

# Token Related
NanoPerThrylos = 10000000
InitialTotalSupply = 120000000

# Staking Related
AnnualStakeReward = 48000000000000
DailyStakeReward = 131506849
MinimumStakeAmount = 400000000
MinStakePercentage = 0.1

# Time Related
RewardDistributionTimeInterval = 86400

# Delegation Related
DelegationRewardPercent = 0.5
